# Generated by Django 2.0.1 on 2018-02-12 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choicename', models.CharField(max_length=200)),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionname', models.CharField(max_length=200)),
                ('pubdate', models.DateTimeField(verbose_name='Published Date')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpoll.question'),
        ),
    ]
